### ISSUE TITLE
Problem with parallel processing of batch_compute method

### ISSUE THREAD

**Issue by HeHelios** [pkomiske/EnergyFlow#12]
I downloaded and tried to run an efp_example.py. I left the code running for a few hours but it seems to stuck at the "Calculating ." It can run and use all the CPU power without any response for hours. I went through console output and it definitely looks like a problem with running parallel processes; one or more are not closed and it causes immediate shutdown by python. Then it tries to reevaluate this part of code and stucks in this loop. I don't know how to extract sole output from console, so attach some screenshots. Sorry for this inconvenience.
![Console_1](https://user-images.githubusercontent.com/55597550/65369706-09565980-dc27-11e9-805c-a145e8ee5a8d.png)
![Console_2](https://user-images.githubusercontent.com/55597550/65369707-09eef000-dc27-11e9-83b1-8cca33bd2377.png)

Also, I attach the output from the jupyter notebook interface (renamed from ipynb to txt). Take into account, please, that evaluation was interrupted.
[Runner_efp.txt](https://github.com/pkomiske/EnergyFlow/files/3638424/Runner_efp.txt)

My setup:
[version.txt](https://github.com/pkomiske/EnergyFlow/files/3638426/version.txt)

Thank You in advance for help!

**Comment by pkomiske** [comment]
I see that you're running this on Windows. I'm going to speculate that this is related to the issue, since python's `multiprocessing` library has some critical differences on Windows compared to Unix-like operating systems (having to do with process creation). When I run the example on my mac with 4 cores, it finishes in just under a minute.

Unfortunately I don't think that I am able to debug whatever is going on, since it runs fine for me and I don't have a Windows setup. In general, it is recommended to run EnergyFlow on Linux, since this is what we and the LHC experiments use for our production-level computing.
