### ISSUE TITLE
qg_nsubs.load fail to download the data

### ISSUE THREAD

**Issue by HeHelios** [pkomiske/EnergyFlow#13]
I am trying to run dnn_example.py and it seems that qg_nsubs.load(...) method can not find a path to download the data. I attach traceback from the output of the jupyter notebook (ipynb renamed to txt) and my system setup.
[Runner_dnn.txt](https://github.com/pkomiske/EnergyFlow/files/3638445/Runner_dnn.txt)
[version.txt](https://github.com/pkomiske/EnergyFlow/files/3638446/version.txt)

Thank You in advance for the help!
Serhii

**Comment by pkomiske** [comment]
Hi Serhii,

Indeed, this seems like a bug! The issue seems to be that the `cache_dir` keyword argument of the `qg_nsubs.load` function defaults to `None`, which is not an allowable path. It should default to something like `'~/.energyflow'`, which is what the `qg_jets.load` function does. I will fix this and it will be released with the next micro version.

In the meantime, explicitly setting `cache_dir` to a path (e.g. `'~/.energyflow'`) should fix this problem.

Thanks for bringing this to our attention!

Cheers,
Patrick

**Comment by pkomiske** [comment]
This has been fixed as of version 1.0.0.
