### ISSUE TITLE
Padding Values

### ISSUE THREAD

**Issue by bnachman** [pkomiske/EnergyFlow#5]
We (@matthewfeickert, @mattleblanc, @kratsg) were finding that the stability of the training is rather dependent on the choice of default value for padding the inputs.  We find that padding with zeros works well, but any other value results in instability.  This sort of makes sense because the network has to learn a nonzero bias in order to make the padding values to not contribute to the sum in the lambda layer.  However, if you pad with zeros, then it doesn't have to learn any bias for the padding values to be ignored in the sum.  One suggestion around this is to have a way to simply ignore padded values in the lambda layer.  Since the default value is application-specific, maybe the padding value could be specified in your initialization?

Thank you for such nice documentation and helpful working examples!

Sincerely,
Ben

**Comment by pkomiske** [comment]
Hi Ben,

I believe that the code already takes care of this, see the `mask_val` argument described [here](https://energyflow.network/docs/archs/#efn). Zero is the default value, so perhaps that's why you were finding that zero works? It's important that the Masking layer is truly ignoring these padded values (whether of value zero or not) so that the biases of the nodes are unaffected by them.

**Comment by matthewfeickert** [comment]
> see the `mask_val` argument described here

Ah, many thanks @pkomiske. This was missed, but should clear up everything.

**Comment by bnachman** [comment]
Indeed, thank you @pkomiske !  That is exactly what we needed.  @matthewfeickert, just to close the loop on our side, we should check that we can change the padding value and also mask_val coherently to achieve stability.  Let's bring this offline.
