### ISSUE TITLE
Examples don't run for num_data < 100000

### ISSUE THREAD

**Issue by mattleblanc** [pkomiske/EnergyFlow#6]
Hi all,

Trying to run e.g. `efp_example.py` from a clean install doesn't work. I get the following:

```
mlb-macbookpro:EMDs mleblanc$ /usr/local/bin/python ~/.energyflow/examples/efp_example.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/mleblanc/.energyflow/examples/efp_example.py", line 54, in <module>
    X, y = qg_jets.load(num_data)
  File "/usr/local/lib/python2.7/site-packages/energyflow/datasets/qg_jets.py", line 132, in load
    max_len_axis1 = max([X.shape[1] for X in Xs])
ValueError: max() arg is an empty sequence
```

If `num_data` on L40 of the example is changed to be >99999, the data files are downloaded and things proceed as expected. I guess this is because `num_data/num_per_file=0` if `num_data<100000`, because we're doing INT division. 

I have fixed it locally with a small hack, but you might want to do something else. I've change L112 in qg_jets.py to be

```
    num_files = int(np.ceil(1.*num_data/num_per_file)) if num_data > -1 else max_num_files
```

... I'm happy to push the fix to the examples if you want!

:beers: MLB

**Comment by pkomiske** [comment]
Hi Matt, 

The issue was not importing `division` from `__future__` (I assume you're using python2 which is where this is an issue). This caused the integer division on L112 whereas I assumed float division. I've pushed a fix in https://github.com/pkomiske/EnergyFlow/commit/9aa5f23e326c719329e816dd3fb9e31fe3cf252f and issued a new PyPI release, `0.11.1`.

Thanks for finding this! 

Cheers,
Patrick
