### ISSUE TITLE
Using advanced activation functions

### ISSUE THREAD

**Issue by kevbauer** [pkomiske/EnergyFlow#7]
Hi, 

I am trying to build a network using a "LeakyReLU" activation function (one of the "advanced" activation functions from Keras (https://keras.io/layers/advanced-activations/)).

However, I am hit with the error: "ValueError: Unknown activation function:LeakyReLU" when calling this: 

"pfn = PFN(input_dim=X.shape[-1], ppm_sizes=ppm_sizes, dense_sizes=dense_sizes, dense_acts='LeakyReLU')"

**Comment by pkomiske** [comment]
Hi @kevbauer,

We did not technically support advanced activations in 0.11.1 and earlier since Keras handles them in such a way that they cannot be simply passed in as strings.

However, I see no good reason to stop users from using advanced activations, so I have added this functionality in 0.11.2 (just released). You can either pass a string such as 'LeakyReLU' and use the default arguments as specified by Keras or you can pass in actual activation layers (allowing you to change the parameters). If you do pass in a layer, be aware that our usual mechanism of repeating choices that are identical across many layers will cause this activation layer to be reused, which may do strange things if, for instance, it has weights (such as with PReLU). In the absence of being certain that it is fine to repeat activation layers, I would just in this case specify a different activation layer per layer in the model.

As usual, let us know if you encounter anything that needs our attention!

Cheers,
Patrick
